### ISSUE TITLE
php-fpm segfault

### ISSUE THREAD

**Issue by zhangchunsheng** [aerospike/aerospike-client-php#123]
__ratelimit: 5 callbacks suppressed
php-fpm[84706]: segfault at 0 ip 00007fca1ac36646 sp 00007fff0cc49080 error 4 in aerospike.so[7fca1abb5000+116000]

Does anybody have this problem in production env? That's terrible.

**Comment by guoxiaod** [comment]
in  /var/log/messages  or the dmesg , we can find messages like this:
Nov 24 18:01:29 uc2 kernel: php-fpm[102317]: segfault at 0 ip 00007f3b0d931646 sp 00007fff307b4a50 error 4 in aerospike.so[7f3b0d8b0000+116000]

we use addr2line tool, got message like this:
$ php -r 'printf("%x\n", 0x7f3b0d931646 - 0x7f3b0d8b0000);'
81646
$ addr2line -fCi -e /usr/lib/debug/usr/lib64/php/modules/aerospike.so.debug 81646
ck_pr_md_load_ptr
/work/source/modules/common/target/Linux-x86_64/include/aerospike/ck/gcc/x86_64/ck_pr.h:162
as_nodes_reserve
/work/source/src/include/aerospike/as_cluster.h:355
aerospike_has_geo
/work/source/src/main/aerospike/aerospike_key.c:887

more informations about the os and php: 

$ php --version
PHP 5.4.41 (cli) (built: May 14 2015 23:37:34) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.5, Copyright (c) 1999-2015, by Zend Technologies

# php-aerospike is compiled on centos 6.7 by ourself
$ rpm -qa php-aerospike
php-aerospike-3.4.10-1.x86_64 

$ gcc --version
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-3)
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ uname -a
Linux xxx.com  2.6.32-358.el6.x86_64 #1 SMP Fri Feb 22 00:31:26 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/redhat-release 
CentOS release 6.4 (Final)

$ ldd /usr/lib64/php/modules/aerospike.so 
	linux-vdso.so.1 =>  (0x00007ffeb03fe000)
	libcrypto.so.10 => /usr/lib64/libcrypto.so.10 (0x00007f2ae2db1000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f2ae2ba9000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f2ae2814000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f2ae3525000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f2ae2610000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f2ae23fa000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f2ae21dc000)

**Comment by koleo** [comment]
@guoxiaod it looks like you are running Aerospike PHP Client v3.4.10.

Some segfaults have been fixed in the latest releases (current version is 3.4.13). Maybe you should upgrade first...

**Comment by guoxiaod** [comment]
@koleo  thanks for  your reply.
The segment fault only occurred on two machine (we have 5 machines) after serveral days after restarting php-fpm.
We first saw the segment fault on v3.4.8, and still exists after upgrading to v3.4.10. 
We will upgrade to v3.4.13 next week, and see if the segment fault will be reproduced.

**Comment by devrck** [comment]
@guoxiaod after upgrading did the issue persist? I have a similar problem and was curious.

**Comment by guoxiaod** [comment]
@devrck  up to now, we have not seen segfault after upgrading aerospike-client-php to 3.4.13 at 2016-12-01

**Comment by guoxiaod** [comment]
we found these backtraces:
#0  0x00007f54a0bbc6e6 in ck_pr_md_load_ptr (target=0x0)
    at modules/common/target/Linux-x86_64/include/aerospike/ck/gcc/x86_64/ck_pr.h:162
#1  as_nodes_reserve (cluster=0x0) at src/include/aerospike/as_cluster.h:355
#2  aerospike_has_geo (as=0x7f54b5639420) at src/main/aerospike/aerospike_key.c:887
#3  0x00007f54a0b5ec25 in zim_Aerospike___construct (execute_data=0x7f54ad413960, return_value=0x7f54ad413920)
    at /usr/src/debug/php-aerospike-3.4.13/src/aerospike/aerospike.c:752

(gdb) f 2
#2  aerospike_has_geo (as=0x7f54b5639420) at src/main/aerospike/aerospike_key.c:887
887				as_nodes_release(nodes);
(gdb) p * as
$5 = {_free = true, cluster = 0x0, config = {user = '\000' <repeats 63 times>, password = '\000' <repeats 63 times>,
    ip_map = 0x0, ip_map_size = 0, max_conns_per_node = 300, async_max_conns_per_node = 300, pipe_max_conns_per_node = 64,
    conn_timeout_ms = 1000, tender_interval = 1000, thread_pool_size = 16, hosts_size = 2, hosts = {{

Is it possible that as->cluster is null ?

**Comment by guoxiaod** [comment]
Today, the segfault happened again  in the product envrionment with 3.4.13

**Comment by guoxiaod** [comment]
Today, the segfault happened again  in the product envrionment with 3.4.13

**Comment by jboone100** [comment]
Same backtrace?

**Comment by guoxiaod** [comment]
the addr2line 's result show that the segfault is same as 3.4.10, and also same as the backtrace (aerospike_has_geo)

```

$ dmesg
php-fpm[75097]: segfault at 0 ip 00007fc6a5543766 sp 00007fff5f899e60 error 4 in aerospike.so[7fc6a54c2000+116000]
php-fpm[75118]: segfault at 0 ip 00007fc6a5543766 sp 00007fff5f899e60 error 4 in aerospike.so[7fc6a54c2000+116000]
php-fpm[75154]: segfault at 0 ip 00007fc6a5543766 sp 00007fff5f899e60 error 4 in aerospike.so[7fc6a54c2000+116000]


$ php -r 'printf("%x\n", 0xfc6a5543766 -  0xfc6a54c2000);'
81766

$ addr2line -fCi -e /usr/lib/debug/usr/lib64/php/modules/aerospike.so.debug 81766
ck_pr_md_load_ptr
/work/source/modules/common/target/Linux-x86_64/include/aerospike/ck/gcc/x86_64/ck_pr.h:162
as_nodes_reserve
/work/source/src/include/aerospike/as_cluster.h:355
aerospike_has_geo
/work/source/src/main/aerospike/aerospike_key.c:887

**Comment by jboone100** [comment]
3.4.14 checks for NULL cluster in the constructor before calling aerospike_has_geo.
